# Generated by Django 3.0.8 on 2020-07-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_websites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='websiteName',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
